#!/bin/bash

current_branch=$(git symbolic-ref --short HEAD 2>/dev/null)

repo_path=$(git rev-parse --show-toplevel)
repo_name=$(basename "$repo_path")

if [[ "$current_branch" == "main" || "$current_branch" == "master" ]] && [[ "$repo_name" != "dotfiles" && "$repo_name" != "jensbech-repo" ]]; then
    echo "ERROR: Committing directly to $current_branch branch is globally disabled."
    echo "Please create a feature branch and commit there instead."
    exit 1
fi

exit 0
