# Alacritty Configuration
# Documentation: https://alacritty.org/config-alacritty.html

[window]
# Window padding (changes require restart)
padding = { x = 8, y = 8 }

# Spread additional padding evenly around the terminal content.
dynamic_padding = false

# Window decorations
decorations = "full"

# Background opacity
opacity = 0.7

# Window title
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title.
dynamic_title = true

[scrolling]
# Maximum number of lines in the scrollback buffer.
history = 10000

# Scrolling distance multiplier.
multiplier = 3

[font]
# Font configuration
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

# Point size of the font
size = 15.0

# Offset is the extra space around each character. `offset.y` can be thought of
# as modifying the line spacing, and `offset.x` as modifying the letter spacing.
offset = { x = 0, y = 0 }

# Glyph offset determines the locations of the glyphs within their cells with
# the default being at the bottom. Increasing `x` moves the glyph to the right,
# increasing `y` moves the glyph upward.
glyph_offset = { x = 0, y = 0 }

# Use built-in font for box drawing characters.
builtin_box_drawing = true

[colors]
# GitHub Dark Theme
[colors.primary]
background = "#0d1117"
foreground = "#e6edf3"
dim_foreground = "#7d8590"
bright_foreground = "#f0f6fc"

# Cursor colors
[colors.cursor]
text = "#0d1117"
cursor = "#f0f6fc"

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "#0d1117"
cursor = "#58a6ff"

# Search colors
[colors.search.matches]
foreground = "#0d1117"
background = "#ffd33d"

[colors.search.focused_match]
foreground = "#0d1117"
background = "#3fb950"

# Keyboard regex hints
[colors.hints.start]
foreground = "#0d1117"
background = "#ffd33d"

[colors.hints.end]
foreground = "#0d1117"
background = "#58a6ff"

# Selection colors
[colors.selection]
text = "#f0f6fc"
background = "#264f78"

# Normal colors
[colors.normal]
black = "#484f58"
red = "#ff7b72"
green = "#3fb950"
yellow = "#d29922"
blue = "#58a6ff"
magenta = "#bc8cff"
cyan = "#39c5cf"
white = "#b1bac4"

# Bright colors
[colors.bright]
black = "#6e7681"
red = "#ffa198"
green = "#56d364"
yellow = "#e3b341"
blue = "#79c0ff"
magenta = "#d2a8ff"
cyan = "#56d4dd"
white = "#f0f6fc"

# Dim colors
[colors.dim]
black = "#21262d"
red = "#f85149"
green = "#238636"
yellow = "#d29922"
blue = "#1f6feb"
magenta = "#8957e5"
cyan = "#0969da"
white = "#b1bac4"

[bell]
# Visual Bell Animation
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[selection]
# This string contains all characters that are used as separators for "semantic words" in Alacritty.
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard.
save_to_clipboard = false

[cursor]
# Cursor style
style = { shape = "Block", blinking = "Off" }

# Vi mode cursor style (falls back to the active value of the normal cursor if "Default")
vi_mode_style = "None"

# Cursor blinking interval in milliseconds.
blink_interval = 750

# Time after which cursor stops blinking, in seconds.
blink_timeout = 5

# If this is `true`, the cursor will be rendered as a hollow box when the
# window is not focused.
unfocused_hollow = true

# Thickness of the cursor relative to the cell width as floating point number
# from `0.0` to `1.0`.
thickness = 0.15

[terminal]
# Controls the OSC 52 behavior for clipboard interactions.
osc52 = "CopyPaste"

[mouse]
# If this is `true`, the cursor is temporarily hidden when typing.
hide_when_typing = false

[keyboard]
# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "SpawnNewInstance"

## Removed Command+Return fullscreen toggle
## (was: action = "ToggleFullscreen")

# Increase font size
[[keyboard.bindings]]
key = "Plus"
mods = "Command"
action = "IncreaseFontSize"

# Decrease font size
[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

# Reset font size
[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

# Disable tab creation and management
[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "W"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Tab"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Tab"
mods = "Command|Shift"
action = "None"

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
action = "None"

[debug]
# Display the time it takes to redraw each frame.
render_timer = false

# Keep the log file after quitting Alacritty.
persistent_logging = false

# Log level
log_level = "Warn"

# Print all received window events.
print_events = false
