theme = "dark_plusplus"

[editor]
end-of-line-diagnostics = "hint" 
bufferline = "always"
color-modes = true

[editor.inline-diagnostics]
cursor-line = "error" 

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"
