[language-server.omnisharp]
command = "/Users/jens/omnisharp-roslyn/OmniSharp"
args = [ "-lsp" ]
timeout = 10000

[language-server.csharp]
command = "csharp-language-server"

[[language]]
name = "c-sharp"
scope = "source.csharp"
file-types = ["cs"]
roots = ["sln", "csproj"]
language-servers = ["omnisharp"]

[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "biome",
]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.ts"] }
